### PR TITLE
Feature/c make options

### PR DESCRIPTION
**Pull request by jowr**
Hi, I changed the build process once more. Changes should be backwards compatible, but CMake 3.0.0 is required now. Is this a problem?

### CODE REVIEW

**Comment by henningjp** [comment]
@jowr The CMake script works good.  Since each wrapper page contains instructions for building the wrapper, I'd remove some clutter and follow the clear CMake instruction format already used previously with this:

***
Accessing IF97 from your software
---------------------------------

There is a `wrapper` directory for 3rd party applications, including:
- [Mathcad 15](wrapper/Mathcad) (Jeff Henning main contributor)
- [Mathcad Prime](wrapper/Mathcad) (Jeff Henning main contributor)

See the README in each wrapper directory for instructions on building and installing each.

Furthermore, there is an interface library target that installs the header file. This target can also be digested by other CMake-based projects using the `add_subdirectory` command. Enable it like this:

```
mkdir buildIL
cd buildIL
cmake .. -DIF97_CMAKE_MODULE=ON
```
***

If I got the intent of the build correct...

**Comment by ibell** [comment]
Pardon my stupidity, but what do you gain with this above and beyond just adding the include to the .h file in another project?

**Comment by jowr** [comment]
You do not gain much here, but I am working on including CoolProp in the Hunter package management for CMake and this requires that all dependencies are "hunterized" as well. The proposed changes make it much easier to add the Hunter-specific code to https://github.com/hunter-packages/IF97 since I do not want them to clutter this repo.

**Comment by ibell** [comment]
Hey @jowr - that seems reasonable; thanks for the explanation.  I have no other comments to make on this one, if you have tested and it works properly, I have no objection to a merge.

**Pull request merged**
