### PR TITLE
Saturation Functions

### PR DESCRIPTION
**Pull request by henningjp**
Added Saturated Vapor and Liquid Functions, both in the IF97.h API definitions as well as the Mathcad wrapper.  See commit notes for details.  The validation PDF in the Mathcad directory shows some continuity plots for specific volume and Enthalpy that demonstrates usage of the saturated liquid/vapor functions.

Saturated vapor/liquid logic requires new enumeration values always remain in a certain order (General, then sat. liquid, then sat vapor).  Added comments to that effect, but it may be fragile.  Open to suggestions on a better method.

### CODE REVIEW

**Comment by ibell** [comment]
I don't understand...  Why is the order of the enumeration important?

**Comment by ibell** [comment]
Also, please do not use tabs, replace all tabs with 4 spaces.  Mixing causes issues, and we have tried to be consistent (though not completely) with 4 spaces instead of tabs.

**Comment by henningjp** [comment]
**Enums:** Look at the output function for region 3.  If it's a vapor function, I force up to a vapor sub-region ( key >= IF97_DVAP ), else if it's a saturated liquid function, I force down to a liquid sub-region ( else if (key >= IF97_DLIQ) ), otherwise it does nothing (this is a general T,p call).  I suppose I could compare to every single VAP enumeration and every single LIQ enumeration, but it's not elegant.  There's doesn't appear to be a nice "if (key IN {Set}) then" operator in C++.  If someone puts the LIQ enumerations before the VAP enumerations in the list, it will break this logic.  Maybe I should write a set of logic functions?
     logical Is_Vapor(key)
     logical Is_Liquid(key)
This would keep the messiness out of the Region 3 output() function.  Thoughts?

**Tabs: **  OK, got it.  Visual Studio does this, but I can switch the behavior to insert spaces. I'll update all the files.  It doesn't take much.  Look for another commit shortly.

**Comment by henningjp** [comment]
Two commits.  Addressed both issues.

**Comment by ibell** [comment]
Why do you have all those new saturation functions which are all almost exactly the same rather than having one for the liquid and another for the vapor with the key of interest passed in.

As usual, try to keep it DRY (https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by ibell** [comment]
Thanks for fixing the indentation as well.

**Comment by henningjp** [comment]
See notes on last commit.  May still be too many API functions, but they fit the "style" of the original six API functions.  CoolProp uses a different paradigm by passing in the desired input/output parameters to a single function, but the IF97 API was not started that way (six separate functions, one for each property call).  I'm happy to go the other way; it's just a style decision of simplicity of the number of functions (with a more complex parameter list) over simplicity of the parameter list with more complex function list.

**Comment by ibell** [comment]
I'm pretty happy with what you did.  It's clean, and I am going to go ahead and merge it.

**Comment by ibell** [comment]
For future work, would you be able to help document the other functions that are not currently documented?

**Comment by henningjp** [comment]
Cool!  No problem, I'll add documentation as I go.  Also, thanks for the code mentoring.  I appreciate it.

**Pull request merged**
