### PR TITLE
Function rho_pX patch

### LINKED ISSUE #16: warning: control may reach end of non-void function [-Wreturn-type]
in function
`inline double rho_pX(double p, double X, IF97parameters inkey)`
missed `return` before 
`RegionOutput(IF97_DMASS, T, p, NONE);`
at the end of function

### PR DESCRIPTION
**Pull request by henningjp**
Patched function rho_pX including:
- return missing on one logic branch
- fixed vapor/liquid logic ( code was copied incorrectly )
- updated logic to determine if in vapor dome
- Added Mathcad stubs for rhops(p,s) and rhoph(p,h) for testing

Patch tested for Enthalpy and Entropy in Regions 1-3 and Region 4.  ( closes #16 )

### CODE REVIEW

**Comment by ibell** [comment]
I merged the other PR first, and now this one has conflicts.  Can you please resolve the conflicts and I'll merge?

**Comment by henningjp** [comment]
OK.  Took me a while to figure out how to resolve the pull/rebase conflicts (learning vimdiff) and get it pushed back (with --force), but I think we're good now.  Updated version string to 2.0.1.

**Comment by thorade** [comment]
Some people consider meld to be more user friendly, but that is of course subjective
http://meldmerge.org/

**Comment by henningjp** [comment]
@thorade Thanks!  I'll look into it.

**Pull request merged**
