### PR TITLE
[header] add algorithm

### PR DESCRIPTION
**Pull request by xoviat**
required for `std::max`

### CODE REVIEW

**Comment by ibell** [comment]
Any chance you can remove the whitespace-only changes?

**Comment by xoviat** [comment]
Actually no. The changes are related to encoding, and I can't edit files without turning them into UTF-8.

**Comment by xoviat** [comment]
I don't actually need this change; as such, closing.

**Comment by jowr** [comment]
I am confused, I made similar changes, should I just merge mine?

**Pull request closed without merging**
